name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab.
# Otherwise, comment out the line below.
# pool: myAgentPool
pool:
  vmImage: ubuntu-18.04


variables:
  python.version: '3.7'
  azureServiceConnectionId: 'Udacity'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: udacity

stages:
#--------------------------------------------#
# BUILD STAGE
#--------------------------------------------#
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    #--------------------------------------------#
    # Use Terraform to create the Infrastructure
    # Install Terraform on the pipeline agent
    - task: TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '1.3.3'

    # Run Terraform Init on the pipeline agent
    - task: TerraformTaskV3@3
      displayName: 'Terrafom init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'anhhv3udacity'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'tfstate'

    # ToDo: Run Terraform Validate
    - task: TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # OPTIONAL - This step is needed only if your Terraform VM uses an SSH key pair for login and you want your pipeline agent to connect to it.
    # Generate an SSH key pair in your local/AZ Cloud shell. Use the public key in the Terraform VM module.
    # Install public key and private key file to the pipeline agent, using the task below.
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '172.173.176.46 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJaR2tjUdYJBTHfgfGRWvlZDMXT3YPFq+nxXudboSpRqxCx7lwEib7EfJA95WsJj6a6xfHRx6+IY171Pxgb/YKm5cWWAYEujTsdHegTdDrPTf4gk5+aU9QpfV3c8503taWLSIzbpywsv9bnjLSQRo7hJv1b1L8eQ+zDx1bIR/MUtQt+5yWi20DnuYnHeLLNPRZFv9RP6yGGzzv+tF4z+u7tH46V3jwhBM0iqiUmtI92204YtEO8hXzBR1ExVvDs93CgBASCtbTGZ2vo/96Ty8MIyko6oqSXT8dzS0zju5r0aRTuLY03YfIrC3JCCVhgeSiLJGketIvJJQvtorKtOhz'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4nMGBfW2r8eCHxa5NwfSNMZIeA1L5KKM+ijfokr/7VnjBFG53tDayBB7gTeiEZV2HfJCv/TWM1vGm7/gIsuljCK3OMDDekmTJqoRKBnXYtHKBlYc1sKzZixGFi0KxrctdZCB1QzmB12OgAWWrfT4Wb8mvvHd/ebwuZ6E06e7Dx+gdYBeBck+peVmPfewzZvgOtByzCmS4T2CqkQuhiQPNO2guSWX0kmZk2xKjE1/EyQKTlPn6WGvrR/4eo5bnyk9MaO+QMMsw0IJ1xzwLlQy2AphSiUxq7zH7754s8VOFOtXMvgpC+l+UZp3AQXhs42EK9WiljBwijXHNao9L5fW7fzBUhHNSuxHoUpqf67i8f8oXBNVxG1sdHIIJI39Gv873sjIo4eavUUEMrLMtMflW9lRsl+TsW6Q41OV6C4zv5+Gh6Dx8+TrCeLnDZiEKF7F3bz8JJqdAW2Kd1Ut/VRcaoi6pPLYtEGXmoC5+04CMk1M/WKbUYmdQeav7ykMYOb0= ahoang@MacBook-Air-3.local'
        sshKeySecureFile: 'id_rsa'

    - task: DownloadSecureFile@1
      name: udacity_public_key
      inputs:
        secureFile: id_rsa
    # Run Terraform Apply
    # ToDo: Change the workingDirectory path, as applicable to you
    - task: TerraformTaskV3@3
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
    # ToDo: Change the workingDirectory path, as applicable to you
    # Destroy the resources in Azure by running a separate pipeline.
    # - task: TerraformTaskV3@3
    #   displayName: Terraform destroy
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'destroy'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    #     environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

  - job: Publishing
    steps:
    #--------------------------------------------#
    # Selenium (UI) Test Suite - Archive the package
    # "ArchiveFiles@2" picks up the web package and archives it.
    - task: ArchiveFiles@2
      displayName: 'Archive UI Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip'
    # Selenium Test Suite - Publish the package
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip   # Same as the archiveFile artifact above.
      displayName: 'Upload Package'
      artifact: drop-uitests

    #--------------------------------------------#
    # FakeRestAPI - Archive
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-FakeRestAPI.zip'
        replaceExistingArchive: true

    # FakeRestAPI - Publish
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-FakeRestAPI.zip
      displayName: Fake Rest API Publish
      artifact: fake-rest-api

    #--------------------------------------------#
    # JMeter (Performance) Test Suite - Archive
    # ToDo: Complete the ArchiveFiles@2 task and publish step
    - task: ArchiveFiles@2
      displayName: 'Archive PerformanceTestSuite'
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/automatedtesting/jmeter/test-suites
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-test-suite.zip'
        replaceExistingArchive: true
    # JMeter Test Suite - Publish
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-test-suite.zip
      displayName: Archive Jmeter Test Suites
      artifact: jmeter-test

#--------------------------------------------#
# DEPLOYMENT STAGE
#--------------------------------------------#
- stage: Deploy
  jobs:
  #--------------------------------------------#
  # Deploy FakeRestAPI Web App
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-18.04'
    environment: udacity
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appType: 'webApp'
              appName: 'anhhv3udacity-AppService'
              package: '$(Pipeline.Workspace)/fake-rest-api/$(Build.BuildId)-FakeRestAPI.zip'
              deploymentMethod: 'zipDeploy'

- stage: Test
  dependsOn: Deploy
  jobs:
  - deployment: JmeterTest
    pool:
      vmImage: 'Ubuntu-18.04'
    environment: udacity
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: Run JMeter Test
            inputs:
              script: |
                echo "================================Install JMeter================================"
                wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip -O apache-jmeter -q
                unzip -qq apache-jmeter
                echo "================================Unzip Test Suites============================="
                unzip -qq $(Build.BuildId)-jmeter-test-suite.zip
                echo "================================Replacing file content========================"
                sed -i -E 's|(.+<stringProp name="filename">).*(/.+.csv</stringProp>)|\1'$(pwd)'\2|' stress-test.jmx
                sed -i -E 's|(.+<stringProp name="filename">).*(/.+.csv</stringProp>)|\1'$(pwd)'\2|' endurance-test.jmx
                echo "================================Execute Tests================================="
                apache-jmeter-5.5/bin/jmeter -n -t endurance-test.jmx
                apache-jmeter-5.5/bin/jmeter -n -t stress-test.jmx
              workingDirectory: $(Pipeline.Workspace)/jmeter-test/

  - job: NewmanTest
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script:           # ToDo: Write your commands to install newman
        workingDirectory: $(System.DefaultWorkingDirectory)
    # Postman Data Validation Test Suite
    - task: CmdLine@2
      displayName: Run Data Validation Tests
      retryCountOnTaskFailure: 10
      continueOnError: true
      inputs:
        script: newman run "Starter APIs.data_validation.json" -x -e "StarterAPITestEnv.postman_environment.json" --delay-request 3000 -r cli,junit --reporter-junit-export $(System.DefaultWorkingDirectory)/test_reports/data_validation.xml
        workingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
    # Postman Regression Test Suite
    - task: CmdLine@2
      displayName: Run Regression Tests
      retryCountOnTaskFailure: 10
      continueOnError: true
      inputs:
        script: newman run "Starter APIs.regression.json" -x -e "StarterAPITestEnv.postman_environment.json" --delay-request 3000 -r cli,junit --reporter-junit-export $(System.DefaultWorkingDirectory)/test_reports/regression.xml
        workingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
    # Postman - Publish Results
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/test_reports/*.xml'
        mergeTestResults: true

  #--------------------------------------------#
  # Selenium | Functional UI Tests
  # ToDo:
  - deployment: VMDeploy
    displayName: Selenium Tests
    environment:
      name: udacity
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
              addToPath: true
              architecture: 'x64'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash

                sudo apt-get upgrade -y
                sudo apt-get update -y
                # sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser

                # export PATH=$PATH:/path/to/chromedriver
                sudo apt-get install -y google-chrome-stable
                # rm -f google-chrome-stable_current_amd64*
                # wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                # sudo apt install ./google-chrome-stable_current_amd64.deb -y

                rm -f chromedriver_linux64*
                wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
                rm -rf chromedriver_linux64
                unzip -qq -o chromedriver_linux64.zip
                sudo mv -f chromedriver /usr/bin/chromedriver
                sudo chown root:root /usr/bin/chromedriver
                sudo chmod +x /usr/bin/chromedriver


                # ToDo: Write commands for deploying the UI Test Suite (published zip artifact) to the linux VM and execute the Test Suite
                # ToDo: Direct the output of the Selenium Test Suite to a log file

                unzip -qq -o $(Build.BuildId)-uitests.zip -d .
                ls -la
                pip3 install selenium
                python3 uitest.py >> uitest.log
              workingDirectory: $(Pipeline.Workspace)/drop-uitests/
