source "azure-arm" "autogenerated_1" {
  azure_tags = {
    task = "Image deployment"
  }

  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "East US"
  managed_image_name                = "azuredevops"
  managed_image_resource_group_name = "Azuredevops"
  os_type                           = "Linux"
  vm_size                           = "Standard_DS1_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    script = "azure-devops.sh"
  }

}