source "azure-arm" "autogenerated_1" {
  azure_tags = {
    task = "Image deployment"
  }

  client_id                         = "91ae7827-9897-45ba-994a-0c48b60dc59b"
  client_secret                     = "ch08Q~kYyzCm-CJJWoRARPsby34jBnsGdtrU~dmY"
  subscription_id                   = "a4b11da3-2642-4ae2-b8e0-ba40545a13d6"
  tenant_id                         = "f958e84a-92b8-439f-a62d-4f45996b6d07"

  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "East US"
  managed_image_name                = "azuredevops"
  managed_image_resource_group_name = "Azuredevops"
  os_type                           = "Linux"
  vm_size                           = "Standard_DS1_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    script = "azure-devops.sh"
  }

}